<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Contratos.aspx.cs" Inherits="teste.Contratos" EnableEventValidation="False" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
  
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
     <div style="float:left;  width:335px">
       
        CLIENTE :
       
        &nbsp;<asp:ListBox ID="ListBox1" runat="server" DataSourceID="MySQLClientes" 
            DataTextField="Nome_cliente" DataValueField="Nome_cliente" 
           
            style="margin-top: 13px" 
             onselectedindexchanged="ListBox1_SelectedIndexChanged" AutoPostBack="True"></asp:ListBox>   
       
         <asp:Button ID="Button7" runat="server" onclick="Button7_Click" 
             Text="Filtrar" Visible="False" />
       
       <p>
        <asp:SqlDataSource ID="clientes" runat="server" 
            ConnectionString="<%$ ConnectionStrings:INVESTSCOPConnectionString %>" 
            SelectCommand="SELECT [Nome_cliente] FROM [Clientes]"></asp:SqlDataSource>
             <asp:SqlDataSource ID="MySQLClientes" runat="server" 
            ConnectionString="<%$ ConnectionStrings:teste %>"
            ProviderName="<%$ ConnectionStrings:teste.ProviderName %>"            
            SelectCommand="SELECT Nome_Cliente  FROM Clientes"></asp:SqlDataSource>
    </p>
     </div>

      <div style="float:left;width:563px; height: 93px;">
          <asp:CheckBox ID="CheckBox1" runat="server" Text="Em Aberto" 
              oncheckedchanged="CheckBox1_CheckedChanged"   
              AutoPostBack="True" />
            &nbsp;<asp:CheckBox ID="CheckBox2" runat="server" Text="Finalizados" 
              oncheckedchanged="CheckBox2_CheckedChanged" AutoPostBack="True" />
            &nbsp;<asp:CheckBox ID="CheckBox3" runat="server" Text="Faturados" 
              oncheckedchanged="CheckBox3_CheckedChanged" AutoPostBack="True" />
            &nbsp;<asp:CheckBox ID="CheckBox4" runat="server" Text="Todos" 
              oncheckedchanged="CheckBox4_CheckedChanged" AutoPostBack="True" 
              Visible="False" />
            &nbsp;
    
            <asp:Button ID="Button8" runat="server" Text="Relatório" Width="114px" 
              onclick="Button8_Click" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:LinkButton ID="LinkButton1" runat="server" OnClientClick="aspnetForm.target ='_blank';"
            onclick="LinkButton1_Click" Visible="False">Último Relatório</asp:LinkButton>
            &nbsp;
            <asp:HyperLink ID="HyperLink1" runat="server" ><a href="temp1.pdf" target="_blank">Último Relatório</a></asp:HyperLink>
            <br />
            <br />
            <asp:FileUpload ID="FileUpload1" runat="server" Width="221px" 
           onload="FileUpload1_Load" Visible="False" />
        <asp:Label ID="Label1" runat="server" Text="Label" Visible="False"></asp:Label>
    
            <asp:Button ID="Button5" runat="server" Text="Finalizar" Width="114px" OnClientClick="return confirm('Deseja mesmo processar e finalizar ?');"
              onclick="Button5_Click" />
        <asp:Label ID="Label3" runat="server" Text="Label" Visible="False"></asp:Label>
      </div>
         <div runat="server" id="theDiv" style="float:left;  width:802px">
             <div style="overflow-y:scroll; width: 802px;  height: 299px">
             <asp:GridView ID="gridcontrato" runat="server" AutoGenerateColumns="False" 
                 Width="578px" 
                 AutoGenerateSelectButton="True" 
                 HorizontalAlign="Center" onrowdatabound="GridView1_RowDataBound" 
                 onselectedindexchanged="GridView1_SelectedIndexChanged" 
                 AutoGenerateDeleteButton="True" onrowdeleting="gridcontrato_RowDeleting">
                 <RowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                 </asp:GridView>
            
             </div>
             <asp:SqlDataSource ID="contrato_sql" runat="server" 
                 ConnectionString="<%$ ConnectionStrings:INVESTSCOPConnectionString %>" 
                 
                 
                 SelectCommand="SELECT [acao], [data_compra], [valor_compra], [qtde_compra], [data_venda], [valor_venda], [qtde_venda], [data_pagamento], [id_contrato], [status] FROM [Contrato]">
             </asp:SqlDataSource>
               <asp:SqlDataSource ID="MySQLContrato" runat="server" 
                 ConnectionString="<%$ ConnectionStrings:teste %>"
            ProviderName="<%$ ConnectionStrings:teste.ProviderName %>"            
            SelectCommand="SELECT acao, data_compra, valor_compra, qtde_compra, data_venda, valor_venda, qtde_venda, data_pagamento, id_contrato, status FROM Clientes"></asp:SqlDataSource>
              
         </div>
         <div style="float:left;width:606px; height: 221px; margin-bottom: 27px;">
             
               <br />
               <br />
             
               Qtde Compra :             
               <asp:TextBox ID="txtqcompra" runat="server"></asp:TextBox>
               &nbsp;&nbsp;&nbsp;&nbsp;
               Valor Compra :
               <asp:TextBox ID="txtvcompra" runat="server"></asp:TextBox>
               <asp:TextBox ID="txtid" runat="server" Height="20px" Visible="False" 
                   Width="67px"></asp:TextBox>
               <br />
               <br />
               Qtde Venda :&nbsp;&nbsp;&nbsp;
               <asp:TextBox ID="txtqvenda" runat="server"></asp:TextBox>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               Valor Venda :
               <asp:TextBox ID="txtvvenda" runat="server"></asp:TextBox>
         &nbsp;<br />
               <br />
               Status :
               <asp:ListBox ID="ListBox2" runat="server" Height="57px">
                   <asp:ListItem Value="A">Em aberto</asp:ListItem>
                   <asp:ListItem Value="F">Finalizados</asp:ListItem>
                   <asp:ListItem Value="P">Faturados</asp:ListItem>
               </asp:ListBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
               Data Pagamento :&nbsp;&nbsp;&nbsp;
               <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
               &nbsp;&nbsp;<br />
               <br />
               &nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="Button6" runat="server" OnClientClick="return confirm('Deseja salvar as informações ?');"
                   Text="Atualizar" Width="91px" onclick="Button6_Click" />
               &nbsp;&nbsp; </div>
</asp:Content>
 