using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.IO;
using System.Text;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using System.Net;
using MySql.Data.MySqlClient;

namespace teste
{
    public partial class Contratos : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Label lbl = this.Master.FindControl("lblMasterPage") as Label;
            string user = lbl.Text;
           // if (user == "")
          //  {
        //        Response.Redirect("Loginuser.aspx", false);
          //  } //  ListBox1.SelectedIndex = -1;

            theDiv.Visible = false;
           
            
        }
        string pdf;
        protected void FileUpload1_Load(object sender, EventArgs e)
        {

        }

        protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
        {
           if (e.Row.RowType == DataControlRowType.DataRow)
            {
                 if (pdf == "1")            
                 {
                
                  e.Row.Cells[9].Font.Bold = true;
                //   gridcontrato.AutoGenerateSelectButton = false;
                //   gridcontrato.AutoGenerateDeleteButton = false;
                   string valor1 = e.Row.Cells[1].Text.ToString();
                   string valor = e.Row.Cells[9].Text.ToString();

                   if (valor == "F")
                   {
                       e.Row.Cells[9].Text = "Finalizado";
                   }
                   else if (valor == "P")
                   {
                       e.Row.Cells[9].Text = "Faturado";
                   }
                 }
                 else

                 {
                     e.Row.Cells[9].Font.Bold = true;
                     
                 }
                  
                }          
        }
        void preenchegrid()
        {

            if (pdf == "1")
            {
                theDiv.Visible = true;
                gridcontrato.Visible = true;
                gridcontrato.DataSource = null;
                gridcontrato.DataBind();
                //define a instrução SQL
                gridcontrato.AutoGenerateDeleteButton = false;
                gridcontrato.AutoGenerateSelectButton = false;
                gridcontrato.AutoGenerateColumns = false;
                gridcontrato.Columns.Clear(); //Remover as colunas
                //Remover as linhas


                if (CheckBox4.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";
                        gridcontrato.Columns.Add(coluna1);
                        
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                      
                        
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;

                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);




                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret;includesecurityasserts=true; ");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
                else if (CheckBox1.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "' AND status LIKE 'A'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }

                }
                else if (CheckBox2.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);


                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "' AND status LIKE 'F'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
                else if (CheckBox3.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "' AND status LIKE 'P'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret;includesecurityasserts=true; ");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
                else
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "Valor Compra";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest(R$)";
                        coluna12.HtmlEncode = false;
                        coluna12.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret;includesecurityasserts=true; ");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();


                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }

                }
            }
            else
            {
                   theDiv.Visible = true;
                gridcontrato.Visible = true;
                gridcontrato.DataSource = null;
                gridcontrato.DataBind();
                //define a instrução SQL

                gridcontrato.AutoGenerateColumns = false;
                gridcontrato.Columns.Clear(); //Remover as colunas
                //Remover as linhas


                if (CheckBox4.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;

                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);




                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
                else if (CheckBox1.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "' AND status LIKE 'A'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }

                }
                else if (CheckBox2.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);


                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "' AND status LIKE 'F'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
                else if (CheckBox3.Checked)
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "valor";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest";
                        coluna12.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "' AND status LIKE 'P'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true; ");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();

                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
                else
                {
                    try
                    {

                        string nome = ListBox1.SelectedItem.ToString();
                        gridcontrato.DataSource = null;
                        gridcontrato.DataBind();
                        //define a instrução SQL

                        gridcontrato.AutoGenerateColumns = false;

                        //define e realiza a formatação de cada coluna
                        BoundField coluna1 = new BoundField();
                        coluna1.DataField = "acao";
                        coluna1.HeaderText = "Ativo";

                        gridcontrato.Columns.Add(coluna1);
                        BoundField coluna2 = new BoundField();
                        coluna2.DataField = "data_compra";
                        coluna2.HeaderText = "Data Compra";
                        coluna2.ReadOnly = true;
                        coluna2.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna2);


                        BoundField coluna3 = new BoundField();
                        coluna3.DataField = "valor_compra";
                        coluna3.HeaderText = "Valor Compra";
                        coluna3.HtmlEncode = false;

                        gridcontrato.Columns.Add(coluna3);

                        BoundField coluna4 = new BoundField();
                        coluna4.DataField = "qtde_compra";
                        coluna4.HeaderText = "Qtde Compra";
                        coluna4.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna4);

                        BoundField coluna5 = new BoundField();
                        coluna5.DataField = "data_venda";
                        coluna5.HeaderText = "Data Venda";
                        coluna5.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna5);

                        BoundField coluna6 = new BoundField();
                        coluna6.DataField = "valor_venda";
                        coluna6.HeaderText = "Valor Venda";
                        coluna6.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna6);

                        BoundField coluna7 = new BoundField();
                        coluna7.DataField = "qtde_venda";
                        coluna7.HeaderText = "Qtde Venda";
                        coluna7.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna7);

                        BoundField coluna8 = new BoundField();
                        coluna8.DataField = "data_pagamento";
                        coluna8.HeaderText = "Data Pagamento";
                        coluna8.HtmlEncode = false;
                        gridcontrato.Columns.Add(coluna8);

                        BoundField coluna9 = new BoundField();
                        coluna9.DataField = "id_contrato";
                        coluna9.HeaderText = "Id";
                        coluna9.HtmlEncode = false;
                        //     coluna9.Visible = false;
                        gridcontrato.Columns.Add(coluna9);

                        BoundField coluna10 = new BoundField();
                        coluna10.DataField = "status";
                        coluna10.HeaderText = "Status";
                        coluna10.HtmlEncode = false;
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna10);

                        BoundField coluna11 = new BoundField();
                        coluna11.DataField = "perccli";
                        coluna11.HeaderText = "% Cliente";
                        coluna11.HtmlEncode = false;
                        coluna11.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna11);


                        BoundField coluna12 = new BoundField();
                        coluna12.DataField = "percinvest";
                        coluna12.HeaderText = "Invest(R$)";
                        coluna12.HtmlEncode = false;
                        coluna12.DataFormatString = "{0:0.00}";
                        //     coluna10.Visible = false;
                        gridcontrato.Columns.Add(coluna12);

                        string strSql2 = "SELECT * From Contrato WHERE nome_cliente LIKE'" + nome + "'";
                        //cria a conexão com o banco de dados
                        MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //cria o objeto command para executar a instruçao sql
                        MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
                        //abre a conexao
                        con.Open();



                        //define o tipo do comando



                        //cria um dataadapter
                        MySqlDataAdapter da = new MySqlDataAdapter(cmd1);
                        DataSet dataset = new DataSet();
                        da.Fill(dataset);
                        //cria um objeto datatable
                        DataTable contrato = new DataTable();

                        //preenche o datatable via dataadapter
                        da.Fill(contrato);
                        da.Fill(dataset, "Contrato");

                        this.gridcontrato.DataSource = dataset;

                        gridcontrato.DataBind();


                        gridcontrato.Enabled = true;
                    }
                    catch
                    {

                    }
                }
            }
        }
        protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
        {
            var grid =gridcontrato as GridView;
            var i = gridcontrato.SelectedIndex + 1;
            //Não lembro, mas acho que a coluna do "Selecionar" conta então comecei com 1    
            txtqcompra.Text = grid.Rows[i].Cells[4].Text;
            txtvcompra.Text = grid.Rows[i].Cells[3].Text;
            txtqvenda.Text = grid.Rows[i].Cells[7].Text;
            txtvvenda.Text = grid.Rows[i].Cells[6].Text;
            string status = grid.Rows[i].Cells[10].Text;
            txtid.Text = grid.Rows[i].Cells[9].Text;

            if (status == "A")
            {
                ListBox2.SelectedIndex = 0;
            }
            else if (status == "F")
            {
                ListBox2.SelectedIndex = 1;
            }
            else
            {
                ListBox2.SelectedIndex = 2;
            }

        }

        protected void ListBox1_SelectedIndexChanged(object sender, EventArgs e)
        {


            CheckBox1.Checked = false;
            CheckBox2.Checked = false;
            CheckBox3.Checked = false;
            CheckBox4.Checked = false;

            preenchegrid();

        }

        protected void Button7_Click(object sender, EventArgs e)
        {
            txtqcompra.Text = "";
            txtvcompra.Text = "";
            txtqvenda.Text = "";
            txtvvenda.Text = "";
            ListBox2.SelectedIndex = -1;
            string nome = ListBox1.SelectedItem.ToString();
            preenchegrid();
          
        }
        private string sumary(string symbol)
        {
            string linha = "";
            string valor = "";
            string simbolo = symbol;
            string[] linhaseparada = null;
            StreamReader reader = new StreamReader((Server.MapPath("~/summary.csv")), true);
            reader.DiscardBufferedData();
            reader.BaseStream.Seek(0, System.IO.SeekOrigin.Begin);
            while (true)
            {
                linha = reader.ReadLine();
                if (linha == null) break;
                linhaseparada = linha.Split(',');
                string resultado = string.Format(
                @"Linha - 
                    Campo 1: {0}
                    Campo 2: {1}
                    Campo 3: {2}
                    Campo 4: {3}
                    Campo 5: {4}", linhaseparada[0], linhaseparada[1], linhaseparada[2], linhaseparada[3], linhaseparada[4]);

                if (linhaseparada[2] == simbolo)
                {
                    valor = linhaseparada[4];

                    break;

                }


            }

            return (valor);


        }
        protected void Button6_Click(object sender, EventArgs e)
        {
            string status = ListBox2.SelectedValue.ToString();
            string qtdevenda = txtqvenda.Text;
            int qtde_v = Convert.ToInt32(qtdevenda);
            string vvenda = txtvvenda.Text;
            string qtdecompra = txtqcompra.Text;
            string vcompra = txtvcompra.Text;
            string datapagamento = TextBox5.Text;
            string id = txtid.Text;
            double investfinal = Convert.ToDouble(qtdevenda);
            double compra = Convert.ToDouble(vcompra);
            double venda = Convert.ToDouble(vvenda);
            double dif = venda - compra;
            double percc = (dif * 100) / compra;
             
            double invest = ((venda - compra) * qtde_v * 0.2);
            string invest_input = string.Format("{0:f2}", percc);
            string rounded_input = string.Format("{0:f2}", invest);
            //   double dif = venda - compra;
            //    double percc = (dif * 100) / compra;
            //     double percin= investfinal*((20 * dif) / 100);



            percc = Math.Round(percc, 2);
            
           


            string sql2 = "UPDATE Contrato SET  valor_compra = @vcompra, qtde_compra= @qtdecompra, valor_venda=@vvenda, qtde_venda=@qtdevenda, status=@status, data_pagamento=@dpagamento, percli=@cli, percinvest=@inv  WHERE id_contrato LIKE'" + id + "'";

            try
            {

                MySqlConnection conn2 = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                MySqlCommand comando = new MySqlCommand(sql2, conn2);
                //Adicionando o valor das textBox nos parametros do comando

                comando.Parameters.Add(new SqlParameter("@status",  status));
                comando.Parameters.Add(new SqlParameter("@vcompra", vcompra));
                comando.Parameters.Add(new SqlParameter("@vvenda", vvenda));
                comando.Parameters.Add(new SqlParameter("@qtdecompra", qtdecompra));
                comando.Parameters.Add(new SqlParameter("@qtdevenda", qtdevenda));
                comando.Parameters.Add(new SqlParameter("@dpagamento", datapagamento));
                comando.Parameters.Add(new SqlParameter("@cli", invest_input));
                comando.Parameters.Add(new SqlParameter("@inv", rounded_input));
                //abre a conexao
                conn2.Open();
                //executa o comando com os parametros que foram adicionados acima
                comando.ExecuteNonQuery();
                //fecha a conexao
                conn2.Close();
                //Minha função para limpar os textBox

                //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
                // referente ao msgbox

            }
            catch
            {

            }
            finally
            {
               
               
            }

            Response.Redirect(Request.Url.AbsoluteUri);


        }

        protected void CheckBox1_CheckedChanged(object sender, EventArgs e)
        {

            CheckBox2.Checked = false;
            CheckBox3.Checked = false;
            CheckBox4.Checked = false;
            preenchegrid();
          
        }

        protected void CheckBox2_CheckedChanged(object sender, EventArgs e)
        {

            CheckBox1.Checked = false;
            CheckBox3.Checked = false;
            CheckBox4.Checked = false;    
            preenchegrid();
           
        }

        protected void CheckBox3_CheckedChanged(object sender, EventArgs e)
        {

            CheckBox2.Checked = false;
            CheckBox1.Checked = false;
            CheckBox4.Checked = false;
            preenchegrid();
          
        }

        protected void CheckBox4_CheckedChanged(object sender, EventArgs e)
        {
           
        }

        protected void Button5_Click(object sender, EventArgs e)
        {
            
            string data_compra = "";
            string qtde_compra = "";
            string valor_compra = "";
            string data_venda = DateTime.Now.ToShortDateString();
           
            string idmov = "";
            string id_cliente = "";
            string nome = "";
            string acao="";
            string valor = "";
            string strSql2 = "SELECT * From movim WHERE status LIKE'A'";
            //cria a conexão com o banco de dados
            MySqlConnection con = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
            //cria o objeto command para executar a instruçao sql
            MySqlCommand cmd1 = new MySqlCommand(strSql2, con);
            //abre a conexao
            con.Open();


            //define o tipo do comando


            MySqlDataReader dr = cmd1.ExecuteReader();

            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    data_compra = dr["data"].ToString();
                    qtde_compra = dr["QTDE"].ToString();
                    valor_compra = dr["valor"].ToString();
                    id_cliente = dr["id_cliente"].ToString();
                    nome = dr["nome"].ToString();
                    acao = dr["ativo"].ToString();
                    idmov = dr["id"].ToString();

                    //    GridView1.Visible = true; 

                    valor = sumary(acao);


                    MySqlConnection conn = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                    //definição do comando sql
                    string sql = "INSERT INTO Contrato(id_cliente, nome_cliente, acao, data_compra, qtde_compra, valor_compra, data_venda, qtde_venda, valor_venda, status ) VALUES (@id_cliente, @nome_cliente, @acao, @data_compra, @qtde_compra, @valor_compra, @data_venda, @qtde_venda, @valor_venda, @status)";

                    try
                    {


                        MySqlCommand comando = new MySqlCommand(sql, conn);
                        //Adicionando o valor das textBox nos parametros do comando

                        comando.Parameters.Add(new SqlParameter("@id_cliente", id_cliente));
                        comando.Parameters.Add(new SqlParameter("@nome_cliente", nome));
                        comando.Parameters.Add(new SqlParameter("@acao", acao));
                        comando.Parameters.Add(new SqlParameter("@data_compra", data_compra));
                        comando.Parameters.Add(new SqlParameter("@qtde_compra", qtde_compra));
                        comando.Parameters.Add(new SqlParameter("@valor_compra", valor_compra));
                        comando.Parameters.Add(new SqlParameter("@data_venda", data_venda));
                        comando.Parameters.Add(new SqlParameter("@qtde_venda", qtde_compra));
                        comando.Parameters.Add(new SqlParameter("@valor_venda", valor));
                        comando.Parameters.Add(new SqlParameter("@status", "F"));

                        //abre a conexao
                        conn.Open();
                        //executa o comando com os parametros que foram adicionados acima
                        comando.ExecuteNonQuery();
                        //fecha a conexao
                        conn.Close();
                        //Minha função para limpar os textBox

                        //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
                        // referente ao msgbox

                    }
                    catch
                    {

                    }
                    finally
                    {

                        MySqlConnection conn3 = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                        //definição do comando sql
                        string sql3 = "DELETE FROM Movim WHERE id LIKE'" + idmov + "'";



                        MySqlCommand comando1 = new MySqlCommand(sql3, conn3);
                        //Adicionando o valor das textBox nos parametros do comando



                        //abre a conexao
                        conn3.Open();
                        //executa o comando com os parametros que foram adicionados acima
                        comando1.ExecuteNonQuery();
                        //fecha a conexao
                        conn3.Close();
                        //definição da string de conexão

                        //Minha função para limpar os textBox

                    }
                }
                Response.Redirect(Request.Url.AbsoluteUri);
            }
        }

        protected void gridcontrato_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            string nome_cliente = "";
            string id_cliente = "";
            string tipo = "Compra";
             
            string id_ativo = "";
            string acao = "";
            string data = "";
            string valor = "";
            string qtde = "";
            
            
            GridViewRow row = (GridViewRow)gridcontrato.Rows[e.RowIndex];

            string id1 = Convert.ToString(gridcontrato.Rows[e.RowIndex].Cells[9].Text);
            //definição da string de conexão
            MySqlConnection conn = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
            //definição do comando sql
            string sql = "SELECT * FROM Contrato WHERE id_contrato LIKE'" + id1 + "'";



            MySqlCommand comando = new MySqlCommand(sql, conn);
            //Adicionando o valor das textBox nos parametros do comando



            //abre a conexao
            conn.Open();
            //executa o comando com os parametros que foram adicionados acima
            comando.ExecuteNonQuery();
            //fecha a conexao
           
            //Minha função para limpar os textBox

            //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
            // referente ao msgbox

            MySqlDataReader dr = comando.ExecuteReader();

            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    nome_cliente = dr["nome_cliente"].ToString();
                    qtde = dr["qtde_compra"].ToString();
                    valor = dr["valor_compra"].ToString();                    
                    data = dr["data_compra"].ToString();
                    acao = dr["acao"].ToString();



                    MySqlConnection conn1 = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true; ");
                    //definição do comando sql
                    string sql1 = "SELECT * FROM Clientes WHERE Nome_cliente LIKE'" + nome_cliente + "'";



                    MySqlCommand comando1 = new MySqlCommand(sql1, conn1);
                    //Adicionando o valor das textBox nos parametros do comando



                    //abre a conexao
                    conn1.Open();
                    //executa o comando com os parametros que foram adicionados acima
                    comando1.ExecuteNonQuery();
                    //fecha a conexao
                    
                    //Minha função para limpar os textBox

                    //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
                    // referente ao msgbox

                    MySqlDataReader dr1 = comando1.ExecuteReader();

                    if (dr1.HasRows)
                    {
                        while (dr1.Read())
                        {
                           id_cliente = dr1["Id_cliente"].ToString();
                            

                        }
                    }

                    conn1.Close();
                    string acao1 = acao.ToString();
                    string[] dadosDoCadastro = acao.Split('-');
                    //  Console.WriteLine(dadosDoCadastro[1]);
                    string split = dadosDoCadastro[1];
                    
                    string id = dadosDoCadastro[0];

                    MySqlConnection conn2 = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true; ");
                    //definição do comando sql
                    string sql2 = "SELECT * FROM Ativos WHERE fname LIKE'" + split + "'";



                    MySqlCommand comando2 = new MySqlCommand(sql2, conn2);
                    //Adicionando o valor das textBox nos parametros do comando



                    //abre a conexao
                    conn2.Open();
                    //executa o comando com os parametros que foram adicionados acima
                    comando2.ExecuteNonQuery();
                    //fecha a conexao
                  
                    //Minha função para limpar os textBox

                    //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
                    // referente ao msgbox

                    MySqlDataReader dr2 = comando2.ExecuteReader();

                    if (dr2.HasRows)
                    {
                        while (dr2.Read())
                        {
                            id_ativo = dr2["id_ativo"].ToString();
                          






                        }
                    }

                    conn2.Close();


                    MySqlConnection conn3 = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                    //definição do comando sql
                    string sql3 = "INSERT INTO Movim( nome, ativo, id_cliente, id_ativo, tipo, data, valor,qtde ) VALUES (@nome, @ativo, @id_cliente, @id_ativo, @tipo, @data, @valor, @qtde)";

                    try
                    {


                        MySqlCommand comando3 = new MySqlCommand(sql3, conn3);
                        //Adicionando o valor das textBox nos parametros do comando

                        comando3.Parameters.Add(new SqlParameter("@nome", nome_cliente));
                        comando3.Parameters.Add(new SqlParameter("@ativo", split));
                        comando3.Parameters.Add(new SqlParameter("@id_cliente", id_cliente));
                        comando3.Parameters.Add(new SqlParameter("@id_ativo", id_ativo));
                        comando3.Parameters.Add(new SqlParameter("@tipo", tipo));
                        comando3.Parameters.Add(new SqlParameter("@data", data));
                        comando3.Parameters.Add(new SqlParameter("@valor", valor));
                        comando3.Parameters.Add(new SqlParameter("@qtde", qtde));

                        //abre a conexao
                        conn3.Open();
                        //executa o comando com os parametros que foram adicionados acima
                        comando3.ExecuteNonQuery();
                        //fecha a conexao
                        conn3.Close();
                        //Minha função para limpar os textBox

                        //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
                        // referente ao msgbox

                    }
                    catch
                    {

                    }
                    finally
                    {
                        conn3.Close();
                        
                    }


                    MySqlConnection conn4 = new MySqlConnection("Server=investscorp.mysql.dbaas.com.br;User Id=investscorp;Database=investscorp;Pwd=Tank76ret; includesecurityasserts=true;");
                    //definição do comando sql
                    string sql4 = "DELETE FROM Contrato WHERE id_contrato LIKE'" + id1 + "'";



                    MySqlCommand comando4 = new MySqlCommand(sql4, conn4);
                    //Adicionando o valor das textBox nos parametros do comando



                    //abre a conexao
                    conn4.Open();
                    //executa o comando com os parametros que foram adicionados acima
                    comando4.ExecuteNonQuery();
                    //fecha a conexao
                    conn4.Close();
                    //Minha função para limpar os textBox

                    //Abaixo temos a ultlização de javascript para apresentar ao usuário um alert
                    // referente ao msgbox


                 
                  




                }
            }

            conn.Close();

            Response.Redirect(Request.Url.AbsoluteUri);




        }
        public override void VerifyRenderingInServerForm(Control control)
        {
            /* Confirms that an HtmlForm control is rendered for the specified ASP.NET
               server control at run time. */
        }
        protected void gridExportToPdf_PageIndexChanging(object sender, GridViewPageEventArgs e)
        {
            gridcontrato.PageIndex = e.NewPageIndex;
             
        }
        protected void Button8_Click(object sender, EventArgs e)
        {
            pdf = "1";
            gridcontrato.DataSource = null;
            gridcontrato.DataBind();
            preenchegrid();
            ExportGridToPDF();
        }


        private void ExportGridToPDF()
    
          {   
            string hoje = DateTime.Now.ToShortDateString() ;
            string hour = DateTime.Now.ToShortTimeString();
            string linha =  ListBox1.SelectedItem.ToString()+ "- "+ hoje + "-" + hour;
            Response.ContentType = "application/pdf";
            Response.AddHeader("content-disposition", "attachment;filename='"+ ListBox1.SelectedItem.ToString() + "-" + hoje +"-"+hour+ "'.pdf");
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            StringWriter sw = new StringWriter();
            HtmlTextWriter hw = new HtmlTextWriter(sw);
           gridcontrato.AllowPaging = false;
           gridcontrato.AutoGenerateSelectButton = false;
           gridcontrato.AutoGenerateDeleteButton = false;
           // gvdetails.DataBind();
           gridcontrato. RowStyle.VerticalAlign = VerticalAlign.Middle;
           gridcontrato.HorizontalAlign = HorizontalAlign.Center;
           gridcontrato.RenderControl(hw);
           gridcontrato.HeaderRow.Style.Add("width", "15%");
           gridcontrato.HeaderRow.Style.Add("font-size", "10px");
           gridcontrato.Style.Add("text-decoration", "none");
           gridcontrato.Style.Add("font-family", "Arial, Helvetica, sans-serif;");
           gridcontrato.Style.Add("font-size", "8px");
           gridcontrato.Style.Add("text-align", "center");
           
            StringReader sr = new StringReader(sw.ToString());
            Document pdfDoc = new Document(PageSize.A2, 7f, 5f, 9f, 0f);
            HTMLWorker htmlparser = new HTMLWorker(pdfDoc);
        
            PdfWriter.GetInstance(pdfDoc, new FileStream((Server.MapPath("~/temp.pdf")), FileMode.Create));
            iTextSharp.text.pdf.draw.VerticalPositionMark seperator = new iTextSharp.text.pdf.draw.LineSeparator();

 
            pdfDoc.Open();
            pdfDoc.Add(new Paragraph(linha));
            pdfDoc.Add(new Paragraph(" "));
            pdfDoc.Add(new Paragraph(" "));

            pdfDoc.Add(seperator);
            htmlparser.Parse(sr);
            pdfDoc.Close();
          
            Response.Write(pdfDoc);


            pdf = "";
            
            Response.Redirect(Request.RawUrl);
    }

        protected void LinkButton1_Click(object sender, EventArgs e)
        {
            string pdfPath = Server.MapPath("~/temp.pdf");
            WebClient client = new WebClient();
            Byte[] buffer = client.DownloadData(pdfPath);
            Response.ContentType = "application/pdf";
            Response.AddHeader("content-length", buffer.Length.ToString());
            Response.BinaryWrite(buffer);
        }
    }
}